Updated files from ship on 13-apr-2020

diff --git a/SHIP_FILES/Royal-Princess/media01/Wowzaunmute b/SHIP_FILES/Royal-Princess/media01/Wowzaunmute
--- a/SHIP_FILES/Royal-Princess/media01/Wowzaunmute
+++ b/SHIP_FILES/Royal-Princess/media01/Wowzaunmute
@@ -1,70 +1,70 @@
+#!/bin/sh
+# processname: WowzaUnmute
 
-
-
-
-
+# Prerequisites:
+# Script needs to be executed by root
 
 start () {
-echo -n "Starting WowzaUnmute..."
+    echo -n "Starting WowzaUnmute..."
 
+    # Start daemon
+    /usr/bin/monit start localhost
+    #curl -so /dev/null http://localhost:8086/uie?action=unmute
 
-/usr/bin/monit start localhost
-
-
-RETVAL=$?
-if [ $RETVAL = 0 ]
-then
-echo "done."
-else
-echo "failed. See error code for more information."
-fi
-return $RETVAL
+    RETVAL=$?
+    if [ $RETVAL = 0 ]
+    then
+        echo "done."
+    else
+        echo "failed. See error code for more information."
+    fi
+    return $RETVAL
 }
 
 stop () {
+    # Stop daemon
+    echo -n "Stopping WowzaUnmute..."
 
-echo -n "Stopping WowzaUnmute..."
+    /usr/bin/monit stop localhost
+    #curl -so /dev/null http://localhost:8086/uie?action=mute
 
-/usr/bin/monit stop localhost
+    RETVAL=$?
 
-
-RETVAL=$?
-
-if [ $RETVAL = 0 ]
-then
-echo "Done."
-else
-echo "Failed. See error code for more information."
-fi
-return $RETVAL
+    if [ $RETVAL = 0 ]
+    then
+        echo "Done."
+    else
+        echo "Failed. See error code for more information."
+    fi
+    return $RETVAL
 }
 
 restart () {
+    # Stop daemon
+    echo -n "Restarting WowzaUnmute..."
 
-echo -n "Restarting WowzaUnmute..."
-
-stop
-start
+    stop
+    start
 }
-
+    
 
 case "$1" in
-start)
-start
-;;
-status)
-status
-;;
-stop)
-stop
-;;
-restart)
-restart
-;;
-*)
-echo $"Usage: WowzaUnmute {start|status|stop|restart}"
-exit 3
-;;
+    start)
+        start
+    ;;
+    status)
+        status
+    ;;
+    stop)
+        stop
+    ;;
+    restart)
+        restart
+    ;;
+    *)
+        echo $"Usage: WowzaUnmute {start|status|stop|restart}"
+        exit 3
+    ;;
 esac
 
 exit $RETVAL
